version: "3.8"
services:
  api:
    depends_on:
      - mongo
    build:
      context: .
      target: "${NODE_ENV}"
      dockerfile: docker/api/Dockerfile
    volumes:
      - ./node_modules:/app/node_modules/
      - ./:/app/
    ports:
      - 3000:3000
  mongo:
    image: mongo:4.4.2-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - 27017:27017
